/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zhevzhyk.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Format {
  UNKNOWN, UNSPECIFIED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Format\",\"namespace\":\"com.zhevzhyk.model\",\"symbols\":[\"UNKNOWN\",\"UNSPECIFIED\"],\"default\":\"UNKNOWN\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
